import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Providers from "@/lib/utils/provider";
import "swiper/css";
import 'swiper/css/navigation';
import 'swiper/css/pagination';

import ReduxProvider from "./ReduxProvider";
import { useAuthState } from "react-firebase-hooks/auth";
import { auth } from "@/lib/utils/firebase";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>
          <body className={montserrat.className}>{children}</body>
        <ReduxProvider/>
      </Providers>
    </html>
  );
}
